### ISSUE TITLE
Updates are not respecting command timeout

### ISSUE THREAD

**Issue by Langes01x** [dotnetprojects/Migrator.NET#30]
When updating data in a table the command timeout specified on the transformation provider doesn't appear to be used. The update still times out after the usual 30 seconds. It should be using the command timeout specified on the provider to be consistent with the other commands.

**Comment by jogibear9988** [comment]
should be fixed

**Comment by Langes01x** [comment]
Doesn't appear like it was fixed. The `Update` method (https://github.com/dotnetprojects/Migrator.NET/blob/master/src/Migrator/Providers/TransformationProvider.cs#L1091) does not create a command using the code that was changed and thus isn't fixed by your change.

**Comment by jogibear9988** [comment]
but now
